In [1]:
# Question 1 Create NumPy array, split into 3 arrays, then calculate sum of all arrays numbers
import numpy as np

arr = np.array([3, 6, 9, 12, 15, 18, 21, 24, 27])

print("Original Array:")
print(arr)

split_arrays = np.array_split(arr, 3)

print("\nSplit Arrays:")
for i, sub_array in enumerate(split_arrays):
    print(f"Array {i+1}: {sub_array}")

total_sum = 0

print("\nSum of each split array:")
for i, sub_array in enumerate(split_arrays):
    sub_sum = np.sum(sub_array)
    print(f"Sum of Array {i+1}: {sub_sum}")
    total_sum += sub_sum

print("\nTotal Sum of All Arrays:", total_sum)


Original Array:
[ 3  6  9 12 15 18 21 24 27]

Split Arrays:
Array 1: [3 6 9]
Array 2: [12 15 18]
Array 3: [21 24 27]

Sum of each split array:
Sum of Array 1: 18
Sum of Array 2: 45
Sum of Array 3: 72

Total Sum of All Arrays: 135


In [2]:
# Question 2 Extract numbers greater than 5 and less than 15
numbers = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18])

print("Original Array:")
print(numbers)

filtered_numbers = numbers[(numbers > 5) & (numbers < 15)]

print("\nNumbers greater than 5 and less than 15:")
print(filtered_numbers)


Original Array:
[ 2  4  6  8 10 12 14 16 18]

Numbers greater than 5 and less than 15:
[ 6  8 10 12 14]


In [3]:
# Question 3 Set Operations
set1 = {0, 2, 4, 6, 8, 10}

set2 = set(range(1, 11))

print("Set1 (Even numbers 0-10):", set1)
print("Set2 (Positive integers 1-10):", set2)

set2_list = list(set2)
set2_list.pop(1)
set2_list.pop(3)

set2 = set(set2_list)

print("\nSet2 after removing 2nd and 5th elements:", set2)

set3 = set1.intersection(set2)

print("Intersection (Set3):", set3)


Set1 (Even numbers 0-10): {0, 2, 4, 6, 8, 10}
Set2 (Positive integers 1-10): {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

Set2 after removing 2nd and 5th elements: {1, 3, 4, 6, 7, 8, 9, 10}
Intersection (Set3): {8, 10, 4, 6}


In [4]:
# Question 4 Create dictionary named students
students = {
    101: {"sapid": 101, "name": "Ali", "age": 21, "semester": "Six"},
    102: {"sapid": 102, "name": "Sami", "age": 22, "semester": "Six"},
    103: {"sapid": 103, "name": "Rehan", "age": 20, "semester": "Six"},
    104: {"sapid": 104, "name": "Aliyar", "age": 23, "semester": "Six"},
    105: {"sapid": 105, "name": "Bilal", "age": 21, "semester": "Six"}
}

print("Original Students Record:")
for key, value in students.items():
    print(value)

for key in students:
    students[key]["semester"] = "Seven"

print("\nUpdated Students Record (Semester Seven):")
for key, value in students.items():
    print(value)


Original Students Record:
{'sapid': 101, 'name': 'Ali', 'age': 21, 'semester': 'Six'}
{'sapid': 102, 'name': 'Sami', 'age': 22, 'semester': 'Six'}
{'sapid': 103, 'name': 'Rehan', 'age': 20, 'semester': 'Six'}
{'sapid': 104, 'name': 'Aliyar', 'age': 23, 'semester': 'Six'}
{'sapid': 105, 'name': 'Bilal', 'age': 21, 'semester': 'Six'}

Updated Students Record (Semester Seven):
{'sapid': 101, 'name': 'Ali', 'age': 21, 'semester': 'Seven'}
{'sapid': 102, 'name': 'Sami', 'age': 22, 'semester': 'Seven'}
{'sapid': 103, 'name': 'Rehan', 'age': 20, 'semester': 'Seven'}
{'sapid': 104, 'name': 'Aliyar', 'age': 23, 'semester': 'Seven'}
{'sapid': 105, 'name': 'Bilal', 'age': 21, 'semester': 'Seven'}
