In [2]:
import numpy as np
print(np.__version__)

2.0.2


In [3]:
import numpy as npy

#1D array
arr = npy.array([1,2,3,4,5])
print(arr)

#2D array
arr1 = npy.array([[1,2,3],[4,5,6]])
print(arr1)

#3D array
arr2 = npy.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr2)

#check number of dimensions
print("The dimension of arr is: ", arr.ndim)
print("The dimension of arr1 is: ",arr1.ndim)
print("The dimension of arr2 is: ",arr2.ndim)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
The dimension of arr is:  1
The dimension of arr1 is:  2
The dimension of arr2 is:  3


In [22]:

arr = npy.array = ([1, 2, 3, 4, 5])
print(arr[0])
print(arr[1])
print(arr[2])

print("Sum of array index 1 and index 3 is : ", arr[1] + arr[3])

1
2
3
Sum of array index 1 and index 3 is :  6


In [ ]:
# slicing in numpy

arr = npy.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])


In [ ]:
# iterating of arrays

# 1D array iteration
arr = npy.array([1, 2, 3, 4, 5])

for x in arr:
    print(x)

# 2D array iteration
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

#3D array iteration
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)


In [ ]:
# Join numpy

# 1D array
arr1 = npy.array([1, 2, 3])
arr2 = npy.array([4, 5, 6])

arr = npy.concatenate((arr1, arr2))

print(arr)

#2D array
arr1 = npy.array([[1, 2], [3, 4]])
arr2 = npy.array([[5, 6], [7, 8]])
arr = npy.concatenate((arr1, arr2), axis=1)

print(arr)




In [ ]:
# Splitting numpy

# 1D array
arr = npy.array([1, 2, 3, 4, 5, 6])
newarr = npy.array_split(arr, 3)

print(newarr)

# 2D array
arr = npy.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = npy.array_split(arr, 3)

print(newarr)



In [ ]:
# numpy searching

arr = npy.array([1, 2, 3, 4, 5, 4, 4])
x = npy.where(arr == 4)

print(x)

# serach where values are even
arr = npy.array([1, 2, 3, 4, 5, 6, 7, 8])
x = npy.where(arr%2 == 0)

print(x)

# serach where values are odd
arr = npy.array([1, 2, 3, 4, 5, 6, 7, 8])
x = npy.where(arr%2 == 1)

print(x)

In [ ]:
# numpy sorting

arr = npy.array([3, 2, 0, 1])

print(npy.sort(arr))

#alphabetically sorting
arr = npy.array(['banana', 'cherry', 'apple'])
print(npy.sort(arr))

In [ ]:
# numpy filter

arr = npy.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]

print(newarr)

In [25]:
# Lab 03 Task

import numpy as np

arr = np.arange(2, 11).reshape(3, 3)

arr = arr.astype(float)

print("3x3 Matrix:")
print(arr)

flat_arr = arr.flatten()

print("Flattened Array:", flat_arr)
print("Maximum value:", np.max(flat_arr))
print("Minimum value:", np.min(flat_arr))


3x3 Matrix:
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
Flattened Array: [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
Maximum value: 10.0
Minimum value: 2.0
